/* This file is automatically generated using python.*/
/* MIGHT be INACCURATE. */
/* License: https://creativecommons.org/licenses/by-nc-sa/4.0/ */
/* GitHub: https://github.com/0xf1c40f/FreeFire-Dumper */
#pragma once
#include <cstdint>

namespace UnityEngine {
namespace Camera {
    constexpr uintptr_t get_fieldOfView = 0x84073d8;
    constexpr uintptr_t set_fieldOfView = 0x8407444;
    constexpr uintptr_t WorldToScreenPoint = 0x84090e4;
    constexpr uintptr_t get_main = 0x84096fc;
}
namespace Component {
    constexpr uintptr_t get_transform = 0x840ba08;
}
namespace Transform {
    constexpr uintptr_t get_position = 0x82bbabc;
    constexpr uintptr_t get_forward = 0x82bc44c;
    constexpr uintptr_t get_rotation = 0x82bbd74;
    constexpr uintptr_t get_position_Injected = 0x82bbaec;
}
}
namespace COW {
namespace GamePlay {
namespace Player {
    constexpr uintptr_t get_NickName = 0x2c5557c;
    constexpr uintptr_t set_m_AimRotation = 0x2c574b0;
    constexpr uintptr_t get_IsDieing = 0x2c4db10;
    constexpr uintptr_t get_HeadCollider = 0x2c58a04;
    constexpr uintptr_t IsVisible = 0x2c5e4ec;
    constexpr uintptr_t IsLocalPlayer = 0x2c46910;
    constexpr uintptr_t IsLocalTeammate = 0x2c74fe8;
    constexpr uintptr_t LateUpdate = 0x2cafac8;
    constexpr uintptr_t GetHeadTF = 0x2cdc088;
    constexpr uintptr_t GetHipTF = 0x2cdc260;
    constexpr uintptr_t IsFiring = 0x2c4e148;
    constexpr uintptr_t get_CurHP = 0x2cc1b10;
    constexpr uintptr_t get_MaxHP = 0x2cc1c4c;
    constexpr uintptr_t get_IsSighting = 0x2c4e200;
}
namespace PhysicsUtil {
    constexpr uintptr_t SingleLineCheck = 0x5452588;
}
}
}
